language: go

go:
  - 1.3

before_install: 
  - go get -u github.com/kyoh86/richgo
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr

script:
  - go build
  - richgo test -v ./...

before_install: go get -u github.com/kyoh86/richgo

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
