language: go

go:
  - 1.x

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install: 
  - go get -u github.com/kyoh86/richgo
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go mod download

script:
  - richgo test -v ./...
  - go build

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username dapi --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
